### PR TITLE
Clean code

### PR DESCRIPTION
**Pull request by ciricode**

### CODE REVIEW

**Comment by ging-dev** [comment]
Ready to merge

**Comment by ciricode** [comment]
> Ready to merge

Maybe

**Comment by ging-dev** [comment]
cc @kenegdane

**Comment by ging-dev** [comment]
Looks like an error will occur if the user passes the http://example.com to `host` parameter

**Comment by ciricode** [comment]
> Looks like an error will occur if the user passes the http://example.com to `host` parameter

Well, I'll think about that.

**Comment by ciricode** [comment]
@ging-dev check inbox

**Comment by kenegdane** [comment]
@ciricode I think you should not use HTTP Client to perform HTTP Flood to the target cuz it's slow than socket very much

**Comment by ging-dev** [comment]
fork it to gingteam @ciricode

**Comment by ciricode** [comment]
> @ciricode I think you should not use net/http cuz it's slow than socket very much

No, http.Request is only used to generate HTTP Header, also the code is not used in official code, please reopen this PR as it is working.

**Pull request merged**
